# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Pinterest-Demo' do
pod 'PINRemoteImage'
pod "PINCache"
pod ‘AFNetworking’
pod ‘MJRefresh’
pod 'MJExtension'
end

target 'Pinterest-DemoUITests' do

end

